### ISSUE TITLE
Questions about the project

### ISSUE THREAD

**Issue by TAN-Gaming** [jakowskidev/uMario_Jakowski#16]
I have some questions about the project
1. Is the entire game source code written from scratch ?
2. What about game assets ? It looks very similar to the NES version.
3. How possible is it to be taken down by Nintendo ?

**Comment by GlowingUmbreon** [comment]
3) Nintendo owns the rights to the assets used and thus have the legal right to take it down if they so wish.

**Comment by TAN-Gaming** [comment]
@GlowingUmbreon OK, thanks.
