### ISSUE TITLE
[Question] Is this a C++ port of the original?

### ISSUE THREAD

**Issue by rraallvv** [jakowskidev/uMario_Jakowski#5]
Sorry to ask, but I'm a bit confused, I'm interested in studying the variable-height jump mechanic in the original Mario Bros game but all I've found is this [6502 disassembled code](https://gist.github.com/1wErt3r/4048722). So I was wondering whether this is a clone built from scratch or rather a port to C++ of the original assembly code? Also, if this is built from scratch I'd like to know how faithful is the jump mechanic to the original?

Keep up the good work.

**Comment by jakowskidev** [comment]
Hi,
it is just my imagination of it, it is not how it was in original game

**Comment by rraallvv** [comment]
I see, thanks for the info, in the video the jump mechanic seems quite similar to the original.
